feat(contributors): automate contributors list in README Closes #48
dipiash/eslint-plugin-nimbus-clean pull request #50
Opened 2023-11-08 10:29 UTC by Aditya-Armal

This commit adds automation to update the list of contributors in the README file. The automation script automatically generates and updates the contributors section based on the project's history.

2023-11-08 17:27 UTC, dipiash requested changes

2023-11-08 17:27 UTC, dipiash commented on README.md
> +### Contributors
Please keep the section `### Contributions`

And add the section `### Contributors` at the bottom of readme

2023-11-08 19:43 UTC, Aditya-Armal commented
Done.

2023-11-09 19:46 UTC, dipiash approved these changes

2023-11-09 19:47 UTC, merged